name: burkina_transport_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+14

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.2
  jaguar_jwt: ^3.0.0
  connectivity_plus: ^3.0.2
  #country_code_picker: ^2.0.2
  sms_autofill: ^2.0.1
  intl: ^0.18.0
  url_launcher: ^6.0.10
  shimmer: ^2.0.0
  in_app_review: ^2.0.3
  #unity_ads_plugin: ^0.3.9
  flutter_bloc: ^8.1.3
  dio: ^5.0.1
  hive: ^2.2.3
  share_plus: ^6.3.4
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  lottie: ^1.2.2
  book_my_seat: ^1.0.1
  omni_datetime_picker: ^1.0.9

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
  pigeon: ^16.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/svgImage/
    - assets/languages/
    - assets/animations/
    - assets/

  fonts:
    - family: Sarabun
      fonts:
        - asset: assets/font/Sarabun-Regular.ttf
          weight: 400
        - asset: assets/font/Sarabun-SemiBold.ttf
          weight: 600
        - asset: assets/font/Sarabun-Light.ttf
          weight: 300
        - asset: assets/font/Sarabun-Medium.ttf
          weight: 500
        - asset: assets/font/Sarabun-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/reewmi_logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true