// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpTw5l7Gx0Hi9Ldz8QOTGvvhRSfUaEsGA',
    appId: '1:831064949419:web:2d1986245bf48836056dee',
    messagingSenderId: '831064949419',
    projectId: 'rahimo-consumer',
    authDomain: 'rahimo-consumer.firebaseapp.com',
    storageBucket: 'rahimo-consumer.appspot.com',
    measurementId: 'G-Q46NZNB0C2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxslgLdxvvi9yV5SIaaWwQGLCNyiAN1w0',
    appId: '1:831064949419:android:3107ce02764ead47056dee',
    messagingSenderId: '831064949419',
    projectId: 'rahimo-consumer',
    storageBucket: 'rahimo-consumer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiS2g_UmB0arje3L4zO_qB4EEHuVc1L40',
    appId: '1:831064949419:ios:f839ae27dbaf1625056dee',
    messagingSenderId: '831064949419',
    projectId: 'rahimo-consumer',
    storageBucket: 'rahimo-consumer.appspot.com',
    androidClientId: '831064949419-327h7q3vsa4p6gtubacrf5ebop1mhfh2.apps.googleusercontent.com',
    iosBundleId: 'com.antm.rahimo.consumer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiS2g_UmB0arje3L4zO_qB4EEHuVc1L40',
    appId: '1:831064949419:ios:b8aabb6ac2db9a22056dee',
    messagingSenderId: '831064949419',
    projectId: 'rahimo-consumer',
    storageBucket: 'rahimo-consumer.appspot.com',
    androidClientId: '831064949419-327h7q3vsa4p6gtubacrf5ebop1mhfh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.burkinaTransportApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpTw5l7Gx0Hi9Ldz8QOTGvvhRSfUaEsGA',
    appId: '1:831064949419:web:3eb30bf20e44e9be056dee',
    messagingSenderId: '831064949419',
    projectId: 'rahimo-consumer',
    authDomain: 'rahimo-consumer.firebaseapp.com',
    storageBucket: 'rahimo-consumer.appspot.com',
    measurementId: 'G-D7QM4FMS0S',
  );
}
